# AWS Terraform Template for pgcopydb Migration Instance
# Generated by PlanetScale Liftoff Migration Reviewer
# Generated on: 2026-04-23
#
# This template creates an EC2 instance pre-configured with pgcopydb
# for PostgreSQL-to-PlanetScale migrations.
#
# Usage:
#   1. Save this file (pgcopydb-migration-instance.tf) and user-data.sh in the same directory
#   2. Run: terraform init
#   3. Run: terraform plan -var="vpc_id=vpc-xxx" -var="subnet_id=subnet-xxx" -var="your_public_ip=$(curl -s icanhazip.com)"
#   4. Run: terraform apply -var="vpc_id=vpc-xxx" -var="subnet_id=subnet-xxx" -var="your_public_ip=$(curl -s icanhazip.com)"

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region
}

# =============================================================================
# Variables
# =============================================================================

variable "resource_prefix" {
  description = "Prefix for all resource names"
  type        = string
  default     = "planetscale-migration"

  validation {
    condition     = can(regex("^[a-z0-9-]+$", var.resource_prefix))
    error_message = "Must be lowercase alphanumeric with hyphens only."
  }
}

variable "vpc_id" {
  description = "VPC ID where the instance will be launched"
  type        = string
}

variable "subnet_id" {
  description = "Public subnet ID with internet gateway route (required for PlanetScale connectivity)"
  type        = string
}

variable "instance_type" {
  description = "EC2 instance type (c7i.xlarge for <100GB, c7i.2xlarge for 100-500GB, c7i.4xlarge for >500GB)"
  type        = string
  default     = "c7i.xlarge"

  validation {
    condition     = can(regex("^c7i\\.", var.instance_type))
    error_message = "Instance type must be c7i family."
  }
}

variable "volume_size" {
  description = "EBS volume size in GB (io2 Block Express)"
  type        = number
  default     = 1000

  validation {
    condition     = contains([500, 1000, 3000, 6000, 12000], var.volume_size)
    error_message = "Volume size must be one of: 500, 1000, 3000, 6000, 12000."
  }
}

variable "key_pair_name" {
  description = "Optional EC2 Key Pair for key-based SSH access. Leave empty to use EC2 Instance Connect only."
  type        = string
  default     = ""
}

variable "your_public_ip" {
  description = "Your public IP address to restrict SSH access (recommended). Leave empty to allow SSH from anywhere. Get your IP from icanhazip.com."
  type        = string
  default     = ""

  validation {
    condition     = var.your_public_ip == "" || can(regex("^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$", var.your_public_ip))
    error_message = "Must be empty or a valid IPv4 address (e.g., 203.0.113.123)."
  }
}

variable "region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

# =============================================================================
# Local Values
# =============================================================================

locals {
  # IOPS mapping matching CloudFormation VolumeConfig
  volume_iops = {
    500   = 30000
    1000  = 40000
    3000  = 50000
    6000  = 60000
    12000 = 70000
  }

  # Source: https://ip-ranges.amazonaws.com/ip-ranges.json (service: EC2_INSTANCE_CONNECT)
  ec2_instance_connect_cidrs = {
    "af-south-1"     = "13.244.121.196/30"
    "ap-east-1"      = "43.198.192.104/29"
    "ap-northeast-1" = "3.112.23.0/29"
    "ap-northeast-2" = "13.209.1.56/29"
    "ap-northeast-3" = "15.168.105.160/29"
    "ap-south-1"     = "13.233.177.0/29"
    "ap-south-2"     = "18.60.252.248/29"
    "ap-southeast-1" = "3.0.5.32/29"
    "ap-southeast-2" = "13.239.158.0/29"
    "ap-southeast-3" = "43.218.193.64/29"
    "ap-southeast-4" = "16.50.248.80/29"
    "ap-southeast-5" = "43.216.87.48/29"
    "ap-southeast-7" = "43.209.155.96/29"
    "ca-central-1"   = "35.183.92.176/29"
    "ca-west-1"      = "40.176.213.168/29"
    "eu-central-1"   = "3.120.181.40/29"
    "eu-central-2"   = "16.63.77.8/29"
    "eu-north-1"     = "13.48.4.200/30"
    "eu-south-1"     = "15.161.135.164/30"
    "eu-south-2"     = "18.101.90.48/29"
    "eu-west-1"      = "18.202.216.48/29"
    "eu-west-2"      = "3.8.37.24/29"
    "eu-west-3"      = "35.180.112.80/29"
    "il-central-1"   = "51.16.183.224/29"
    "me-central-1"   = "3.29.147.40/29"
    "me-south-1"     = "16.24.46.56/29"
    "mx-central-1"   = "78.12.207.8/29"
    "sa-east-1"      = "18.228.70.32/29"
    "us-east-1"      = "18.206.107.24/29"
    "us-east-2"      = "3.16.146.0/29"
    "us-west-1"      = "13.52.6.112/29"
    "us-west-2"      = "18.237.140.160/29"
  }
  ec2_instance_connect_cidr = lookup(local.ec2_instance_connect_cidrs, var.region, "18.206.107.24/29")

  tags = {
    Name    = "${var.resource_prefix}-ec2"
    Purpose = "PostgreSQL to PlanetScale Migration"
  }
}

# =============================================================================
# AMI Lookup - Ubuntu 24.04 LTS (same as CloudFormation SSM parameter)
# =============================================================================

data "aws_ssm_parameter" "ubuntu_ami" {
  name = "/aws/service/canonical/ubuntu/server/24.04/stable/current/amd64/hvm/ebs-gp3/ami-id"
}

# =============================================================================
# IAM Role + Instance Profile
# =============================================================================

resource "aws_iam_role" "instance_role" {
  name = "${var.resource_prefix}-ec2-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Principal = {
          Service = "ec2.amazonaws.com"
        }
        Action = "sts:AssumeRole"
      }
    ]
  })

  tags = merge(local.tags, {
    Name = "${var.resource_prefix}-ec2-role"
  })
}

resource "aws_iam_role_policy_attachment" "cloudwatch" {
  role       = aws_iam_role.instance_role.name
  policy_arn = "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
}

resource "aws_iam_role_policy_attachment" "ssm" {
  role       = aws_iam_role.instance_role.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_instance_profile" "instance_profile" {
  name = "${var.resource_prefix}-ec2-profile"
  role = aws_iam_role.instance_role.name
}

# =============================================================================
# Security Group
# =============================================================================

resource "aws_security_group" "pgcopydb" {
  name_prefix = "${var.resource_prefix}-sg"
  description = "Security group for pgcopydb migration instance"
  vpc_id      = var.vpc_id

  tags = merge(local.tags, {
    Name = "${var.resource_prefix}-sg"
  })
}

resource "aws_vpc_security_group_egress_rule" "all_outbound" {
  security_group_id = aws_security_group.pgcopydb.id
  description       = "Allow all outbound traffic"
  ip_protocol       = "-1"
  cidr_ipv4         = "0.0.0.0/0"
}

resource "aws_vpc_security_group_ingress_rule" "ssh" {
  security_group_id = aws_security_group.pgcopydb.id
  description       = var.your_public_ip != "" ? "SSH restricted to ${var.your_public_ip}" : "SSH open to all (specify your_public_ip to restrict)"
  ip_protocol       = "tcp"
  from_port         = 22
  to_port           = 22
  cidr_ipv4         = var.your_public_ip != "" ? "${var.your_public_ip}/32" : "0.0.0.0/0"
}

resource "aws_vpc_security_group_ingress_rule" "ec2_instance_connect" {
  security_group_id = aws_security_group.pgcopydb.id
  description       = "EC2 Instance Connect service IP range for ${var.region}"
  ip_protocol       = "tcp"
  from_port         = 22
  to_port           = 22
  cidr_ipv4         = local.ec2_instance_connect_cidr
}

resource "aws_vpc_security_group_ingress_rule" "icmp_dest_unreachable" {
  security_group_id = aws_security_group.pgcopydb.id
  description       = "ICMP Destination Unreachable for path MTU discovery"
  ip_protocol       = "icmp"
  from_port         = 3
  to_port           = -1
  cidr_ipv4         = "0.0.0.0/0"
}

# =============================================================================
# EC2 Instance
# =============================================================================

resource "aws_instance" "pgcopydb" {
  ami                    = data.aws_ssm_parameter.ubuntu_ami.value
  instance_type          = var.instance_type
  key_name               = var.key_pair_name != "" ? var.key_pair_name : null
  iam_instance_profile   = aws_iam_instance_profile.instance_profile.name
  subnet_id                   = var.subnet_id
  vpc_security_group_ids      = [aws_security_group.pgcopydb.id]
  associate_public_ip_address = true

  root_block_device {
    volume_size           = var.volume_size
    volume_type           = "io2"
    iops                  = local.volume_iops[var.volume_size]
    delete_on_termination = true
    encrypted             = true
  }

  metadata_options {
    http_tokens                 = "required"
    http_put_response_hop_limit = 1
  }

  user_data = file("${path.module}/user-data.sh")

  tags = local.tags

  depends_on = [
    aws_iam_role_policy_attachment.cloudwatch,
    aws_iam_role_policy_attachment.ssm,
  ]
}

# =============================================================================
# Outputs
# =============================================================================

output "instance_id" {
  description = "EC2 Instance ID"
  value       = aws_instance.pgcopydb.id
}

output "public_ip" {
  description = "Public IP address (for PlanetScale connectivity)"
  value       = aws_instance.pgcopydb.public_ip
}

output "private_ip" {
  description = "Private IP address (for VPC database connectivity)"
  value       = aws_instance.pgcopydb.private_ip
}

output "security_group_id" {
  description = "Security Group ID"
  value       = aws_security_group.pgcopydb.id
}

output "ssh_command" {
  description = "SSH connection command"
  value       = var.key_pair_name != "" ? "ssh -i /path/to/${var.key_pair_name}.pem ubuntu@${aws_instance.pgcopydb.public_ip}" : "Use EC2 Instance Connect or Session Manager"
}

output "ec2_instance_connect_command" {
  description = "EC2 Instance Connect command (no key required)"
  value       = "aws ec2-instance-connect send-ssh-public-key --instance-id ${aws_instance.pgcopydb.id} --instance-os-user ubuntu --ssh-public-key file://~/.ssh/id_rsa.pub"
}

output "session_manager_command" {
  description = "AWS Session Manager connection command"
  value       = "aws ssm start-session --target ${aws_instance.pgcopydb.id}"
}

output "quick_start" {
  description = "Quick start guide"
  value       = <<-EOT
    1. Connect via EC2 Instance Connect or SSH
    2. Verify: pgcopydb --version
    3. See ~/README.md for usage instructions
  EOT
}
