# Azure Terraform Template for pgcopydb Migration Instance
# Generated by PlanetScale Liftoff Migration Reviewer
# Generated on: 2026-09-11
#
# This template creates an Azure VM pre-configured with pgcopydb
# for PostgreSQL-to-PlanetScale migrations.
#
# Usage:
#   1. Save this file (pgcopydb-migration-instance.tf) and custom-data.sh in the same directory
#   2. Run: terraform init
#   3. Run: terraform plan -var="subscription_id=xxx" -var="vnet_resource_group_name=xxx" -var="vnet_name=xxx" -var="subnet_name=xxx" -var="your_public_ip=$(curl -s icanhazip.com)"
#   4. Run: terraform apply -var="subscription_id=xxx" -var="vnet_resource_group_name=xxx" -var="vnet_name=xxx" -var="subnet_name=xxx" -var="your_public_ip=$(curl -s icanhazip.com)"

terraform {
  required_version = ">= 1.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }
}

provider "azurerm" {
  features {}

  subscription_id = var.subscription_id
}

# =============================================================================
# Variables
# =============================================================================

variable "subscription_id" {
  description = "Azure subscription ID where the migration instance will be created"
  type        = string
}

variable "resource_prefix" {
  description = "Prefix for all resource names"
  type        = string
  default     = "planetscale-migration"

  validation {
    condition     = can(regex("^[a-z][-a-z0-9]*$", var.resource_prefix))
    error_message = "Resource prefix must start with lowercase letter and contain only lowercase letters, numbers, and hyphens."
  }
}

variable "location" {
  description = "Azure region for resources. Must support zonal Premium SSD v2 disks."
  type        = string
  default     = "eastus"
}

variable "zone" {
  description = "Availability zone for the VM and its data disk. Premium SSD v2 disks can only attach to a VM in the same zone."
  type        = string
  default     = "1"

  validation {
    condition     = contains(["1", "2", "3"], var.zone)
    error_message = "Zone must be 1, 2, or 3."
  }
}

variable "vnet_resource_group_name" {
  description = "Name of the existing resource group that holds your virtual network"
  type        = string
}

variable "vnet_name" {
  description = "Name of existing virtual network"
  type        = string
}

variable "subnet_name" {
  description = "Name of existing subnet with outbound internet access (required for PlanetScale connectivity)"
  type        = string
}

variable "vm_size" {
  description = "VM size. This sets migration throughput: data disk IOPS are provisioned to match the size's NVMe ceiling (E4bds=21k, E8bds=44k, E16bds=80k IOPS)."
  type        = string
  default     = "Standard_E8bds_v5"

  validation {
    condition     = can(regex("^Standard_E(4|8|16)bds_v5$", var.vm_size))
    error_message = "VM size must be Standard_E4bds_v5, Standard_E8bds_v5, or Standard_E16bds_v5."
  }
}

variable "data_disk_size_gb" {
  description = "Premium SSD v2 data disk size in GB. Capacity only — disk IOPS are derived from var.vm_size."
  type        = number
  default     = 1000

  validation {
    condition     = contains([500, 1000, 3000], var.data_disk_size_gb)
    error_message = "Data disk size must be one of: 500, 1000, 3000."
  }
}

variable "os_disk_size_gb" {
  description = "OS disk size in GB. Only holds the OS and build artifacts; migration data lives on the data disk."
  type        = number
  default     = 128

  validation {
    condition     = var.os_disk_size_gb >= 64 && var.os_disk_size_gb <= 512
    error_message = "OS disk size must be between 64 and 512 GB."
  }
}

variable "ssh_public_key" {
  description = "SSH public key for accessing the VM. If omitted, a throwaway key is generated (Azure requires one) and you connect with `az ssh vm` instead."
  type        = string
  default     = null
}

variable "your_public_ip" {
  description = "Your public IP address to restrict SSH access (recommended). Leave null to allow SSH from anywhere. Get your IP from icanhazip.com."
  type        = string
  default     = null

  validation {
    condition     = var.your_public_ip == null || can(regex("^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$", var.your_public_ip))
    error_message = "Must be null or a valid IPv4 address (e.g., 203.0.113.123)."
  }
}

variable "grant_ssh_login_to_deployer" {
  description = "Grant the account running Terraform the Virtual Machine Administrator Login role, so `az ssh vm` works immediately. Set false if you lack permission to create role assignments."
  type        = bool
  default     = true
}

variable "install_azure_monitor_agent" {
  description = "Install the Azure Monitor Agent extension. Off by default: it collects nothing without a Data Collection Rule, and it is a known source of dpkg lock contention during first boot."
  type        = bool
  default     = false
}

# =============================================================================
# Local Values
# =============================================================================

locals {
  vm_disk_performance = {
    "Standard_E4bds_v5"  = { iops = 21000, mbps = 600 }  # VM ceiling 21,400 / 600
    "Standard_E8bds_v5"  = { iops = 44000, mbps = 1200 } # VM ceiling 44,200 / 1,200
    "Standard_E16bds_v5" = { iops = 80000, mbps = 2000 } # VM ceiling 88,400 / 2,300 — disk caps first
  }

  disk_performance = local.vm_disk_performance[var.vm_size]

  admin_ssh_public_key = coalesce(var.ssh_public_key, one(tls_private_key.migration[*].public_key_openssh))

  tags = {
    Name    = "${var.resource_prefix}-vm"
    Purpose = "PostgreSQL to PlanetScale Migration"
  }
}

# =============================================================================
# Data Sources - Existing Network
# =============================================================================

data "azurerm_subnet" "migration" {
  name                 = var.subnet_name
  virtual_network_name = var.vnet_name
  resource_group_name  = var.vnet_resource_group_name
}

data "azurerm_client_config" "current" {}

# =============================================================================
# Resource Group
# =============================================================================

resource "azurerm_resource_group" "migration" {
  name     = "${var.resource_prefix}-rg"
  location = var.location

  tags = local.tags
}

# =============================================================================
# Network Security Group
# =============================================================================

resource "azurerm_network_security_group" "migration" {
  name                = "${var.resource_prefix}-nsg"
  location            = azurerm_resource_group.migration.location
  resource_group_name = azurerm_resource_group.migration.name

  tags = local.tags
}

resource "azurerm_network_security_rule" "ssh" {
  name                        = "AllowSSHInbound"
  description                 = var.your_public_ip != null ? "SSH restricted to ${var.your_public_ip}" : "SSH open to all (specify your_public_ip to restrict)"
  priority                    = 100
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_range      = "22"
  source_address_prefix       = var.your_public_ip != null ? "${var.your_public_ip}/32" : "*"
  destination_address_prefix  = "*"
  resource_group_name         = azurerm_resource_group.migration.name
  network_security_group_name = azurerm_network_security_group.migration.name
}

resource "azurerm_network_security_rule" "icmp" {
  name                        = "AllowIcmpInbound"
  description                 = "ICMP for path MTU discovery"
  priority                    = 110
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Icmp"
  source_port_range           = "*"
  destination_port_range      = "*"
  source_address_prefix       = "*"
  destination_address_prefix  = "*"
  resource_group_name         = azurerm_resource_group.migration.name
  network_security_group_name = azurerm_network_security_group.migration.name
}

resource "azurerm_network_security_rule" "outbound" {
  name                        = "AllowAllOutbound"
  description                 = "Allow all outbound traffic"
  priority                    = 100
  direction                   = "Outbound"
  access                      = "Allow"
  protocol                    = "*"
  source_port_range           = "*"
  destination_port_range      = "*"
  source_address_prefix       = "*"
  destination_address_prefix  = "*"
  resource_group_name         = azurerm_resource_group.migration.name
  network_security_group_name = azurerm_network_security_group.migration.name
}

# =============================================================================
# Public IP + NIC
# =============================================================================

resource "azurerm_public_ip" "migration" {
  name                = "${var.resource_prefix}-pip"
  location            = azurerm_resource_group.migration.location
  resource_group_name = azurerm_resource_group.migration.name
  allocation_method   = "Static"
  sku                 = "Standard"
  zones               = [var.zone]

  tags = local.tags
}

resource "azurerm_network_interface" "migration" {
  name                           = "${var.resource_prefix}-nic"
  location                       = azurerm_resource_group.migration.location
  resource_group_name            = azurerm_resource_group.migration.name
  accelerated_networking_enabled = true

  ip_configuration {
    name                          = "internal"
    subnet_id                     = data.azurerm_subnet.migration.id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = azurerm_public_ip.migration.id
  }

  tags = local.tags
}

resource "azurerm_network_interface_security_group_association" "migration" {
  network_interface_id      = azurerm_network_interface.migration.id
  network_security_group_id = azurerm_network_security_group.migration.id
}

# =============================================================================
# SSH Key
# =============================================================================

resource "tls_private_key" "migration" {
  count = var.ssh_public_key == null ? 1 : 0

  algorithm = "RSA"
  rsa_bits  = 4096
}

# =============================================================================
# Virtual Machine
# =============================================================================

resource "azurerm_linux_virtual_machine" "migration" {
  name                = "${var.resource_prefix}-vm"
  location            = azurerm_resource_group.migration.location
  resource_group_name = azurerm_resource_group.migration.name
  size                = var.vm_size
  zone                = var.zone

  # The helper scripts and custom-data.sh hardcode /home/ubuntu, so the admin
  # user must be "ubuntu" rather than Azure's usual "azureuser".
  admin_username                  = "ubuntu"
  disable_password_authentication = true

  network_interface_ids = [azurerm_network_interface.migration.id]

  disk_controller_type = "NVMe"

  identity {
    type = "SystemAssigned"
  }

  admin_ssh_key {
    username   = "ubuntu"
    public_key = local.admin_ssh_public_key
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Premium_LRS"
    disk_size_gb         = var.os_disk_size_gb
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "ubuntu-24_04-lts"
    sku       = "server"
    version   = "latest"
  }

  custom_data = base64encode(file("${path.module}/custom-data.sh"))

  tags = local.tags
}

# =============================================================================
# Data Disk
# =============================================================================

resource "azurerm_managed_disk" "migration_data" {
  name                 = "${var.resource_prefix}-data-disk"
  location             = azurerm_resource_group.migration.location
  resource_group_name  = azurerm_resource_group.migration.name
  storage_account_type = "PremiumV2_LRS"
  create_option        = "Empty"
  disk_size_gb         = var.data_disk_size_gb
  zone                 = var.zone

  disk_iops_read_write = local.disk_performance.iops
  disk_mbps_read_write = local.disk_performance.mbps

  tags = local.tags
}

resource "azurerm_virtual_machine_data_disk_attachment" "migration_data" {
  managed_disk_id    = azurerm_managed_disk.migration_data.id
  virtual_machine_id = azurerm_linux_virtual_machine.migration.id
  lun                = 0

  # Premium SSD v2 does not support host caching.
  caching = "None"
}

# =============================================================================
# VM Extensions + Role Assignment
# =============================================================================

resource "azurerm_virtual_machine_extension" "aad_ssh_login" {
  name                       = "AADSSHLoginForLinux"
  virtual_machine_id         = azurerm_linux_virtual_machine.migration.id
  publisher                  = "Microsoft.Azure.ActiveDirectory"
  type                       = "AADSSHLoginForLinux"
  type_handler_version       = "1.0"
  auto_upgrade_minor_version = true

  tags = local.tags
}

resource "azurerm_role_assignment" "ssh_login" {
  count = var.grant_ssh_login_to_deployer ? 1 : 0

  scope                = azurerm_linux_virtual_machine.migration.id
  role_definition_name = "Virtual Machine Administrator Login"
  principal_id         = data.azurerm_client_config.current.object_id
}

resource "azurerm_virtual_machine_extension" "azure_monitor" {
  count = var.install_azure_monitor_agent ? 1 : 0

  name                       = "AzureMonitorLinuxAgent"
  virtual_machine_id         = azurerm_linux_virtual_machine.migration.id
  publisher                  = "Microsoft.Azure.Monitor"
  type                       = "AzureMonitorLinuxAgent"
  type_handler_version       = "1.0"
  auto_upgrade_minor_version = true

  tags = local.tags
}

# =============================================================================
# Outputs
# =============================================================================

output "vm_name" {
  description = "Name of the virtual machine"
  value       = azurerm_linux_virtual_machine.migration.name
}

output "vm_id" {
  description = "Resource ID of the virtual machine"
  value       = azurerm_linux_virtual_machine.migration.id
}

output "resource_group_name" {
  description = "Resource group holding the migration instance"
  value       = azurerm_resource_group.migration.name
}

output "public_ip" {
  description = "Public IP address (for PlanetScale connectivity)"
  value       = azurerm_public_ip.migration.ip_address
}

output "private_ip" {
  description = "Private IP address (for VNet database connectivity)"
  value       = azurerm_network_interface.migration.private_ip_address
}

output "location" {
  description = "Azure region where the VM is deployed"
  value       = azurerm_linux_virtual_machine.migration.location
}

output "zone" {
  description = "Availability zone where the VM is deployed"
  value       = azurerm_linux_virtual_machine.migration.zone
}

output "managed_identity_principal_id" {
  description = "Principal ID of the VM's system-assigned managed identity"
  value       = azurerm_linux_virtual_machine.migration.identity[0].principal_id
}

output "data_disk_iops" {
  description = "Provisioned data disk IOPS (matched to the VM size's NVMe ceiling)"
  value       = local.disk_performance.iops
}

output "data_disk_throughput_mbps" {
  description = "Provisioned data disk throughput in MB/s"
  value       = local.disk_performance.mbps
}

output "ssh_command" {
  description = "Connect as ubuntu — the account the migration tooling is installed under"
  value = var.ssh_public_key != null ? (
    "ssh ubuntu@${azurerm_public_ip.migration.ip_address}"
    ) : join(" ", [
      "terraform output -raw generated_ssh_private_key > ./migration_key &&",
      "chmod 600 ./migration_key &&",
      "ssh -i ./migration_key ubuntu@${azurerm_public_ip.migration.ip_address}"
  ])
}

output "entra_ssh_command" {
  description = "Keyless fallback via Entra ID. Logs in as your own account, not ubuntu, so follow it with 'sudo su - ubuntu' to reach the tooling."
  value       = "az ssh vm --name ${azurerm_linux_virtual_machine.migration.name} --resource-group ${azurerm_resource_group.migration.name}"
}

output "run_command_example" {
  description = "Run a command on the VM without inbound network access"
  value       = "az vm run-command invoke --resource-group ${azurerm_resource_group.migration.name} --name ${azurerm_linux_virtual_machine.migration.name} --command-id RunShellScript --scripts 'pgcopydb --version'"
}

output "portal_url" {
  description = "Azure portal URL for the VM"
  value       = "https://portal.azure.com/#@/resource${azurerm_linux_virtual_machine.migration.id}/overview"
}

output "migration_scripts_path" {
  description = "Path to the migration helper scripts on the VM"
  value       = "/home/ubuntu/"
}

output "generated_ssh_private_key" {
  description = "Throwaway private key generated when ssh_public_key was not supplied. Retrieve with: terraform output -raw generated_ssh_private_key"
  value       = one(tls_private_key.migration[*].private_key_openssh)
  sensitive   = true
}

output "quick_start" {
  description = "Quick start instructions"
  value       = <<-EOT
    🚀 Quick Start Guide:

    1. Wait 10-15 minutes for VM initialization to complete
       (pgcopydb is built from source on first boot)

    2. Connect as ubuntu (the account the tooling is installed under):
       ${var.ssh_public_key != null ? "ssh ubuntu@${azurerm_public_ip.migration.ip_address}" : "terraform output -raw generated_ssh_private_key > ./migration_key && chmod 600 ./migration_key\n       ssh -i ./migration_key ubuntu@${azurerm_public_ip.migration.ip_address}"}

       Keyless via Entra ID, but logs in as you — add 'sudo su - ubuntu':
       az ssh vm --name ${azurerm_linux_virtual_machine.migration.name} --resource-group ${azurerm_resource_group.migration.name}

    3. Check installation logs:
       sudo tail -f /var/log/pgcopydb-setup.log

    4. Verify installations:
       pgcopydb --version
       psql --version
       df -h /home/ubuntu   # should show the ${var.data_disk_size_gb} GB data disk

    5. See ~/README.md for usage instructions

    📖 Helper scripts location: /home/ubuntu/
    💾 Data disk: ${var.data_disk_size_gb} GB Premium SSD v2 @ ${local.disk_performance.iops} IOPS / ${local.disk_performance.mbps} MB/s
    🌐 Portal: https://portal.azure.com/#@/resource${azurerm_linux_virtual_machine.migration.id}/overview
  EOT
}
